INSERT INTO ourassembly.committee (id, name) VALUES (1, '교육위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (2, '국방위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (3, '기후위기 특별위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (4, '기후에너지환경노동위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (5, '정무위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (6, '윤석열정부의비상계엄선포를통한내란혐의진상규명국정조사특별위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (7, '국회운영위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (8, '외교통일위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (9, '예산결산특별위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (10, '산업통상자원중소벤처기업위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (11, '문화체육관광위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (12, '행정안전위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (13, '법제사법위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (14, '순직 해병 수사 방해 및 사건 은폐 등의 진실규명을 위한 국정조사특별위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (15, '윤석열 정권 정치검찰 조작기소 의혹 사건 진상규명 국정조사특별위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (16, '보건복지위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (17, '정보위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (18, '재정경제기획위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (19, '국토교통위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (20, '연금개혁 특별위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (21, '성평등가족위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (22, '정치개혁특별위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (23, '농림축산식품해양수산위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (24, '과학기술정보방송통신위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (25, '산불피해지원대책 특별위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (26, '기획재정위원회');
INSERT INTO ourassembly.committee (id, name) VALUES (27, '2025 아시아태평양경제협력체(APEC) 정상회의 지원 특별위원회');
