package com.team3.ourassembly.domain.news.service;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * 뉴스 원문 URL을 화면에 보여줄 언론사명으로 매핑하는 유틸.
 * 상세 매핑 규칙은 이 테이블에 계속 추가하면 된다.
 */
public final class NewsCompanyMapper {
    private static final Map<String, String> COMPANY_RULES = new LinkedHashMap<>();

    static {
        COMPANY_RULES.put("newsis","뉴시스");
        COMPANY_RULES.put("news1","뉴스원");
        COMPANY_RULES.put("nocutnews", "노컷뉴스");
        COMPANY_RULES.put("newspim","뉴스핌");
        COMPANY_RULES.put("kbs", "KBS");
        COMPANY_RULES.put("heraldcorp", "헤럴드경제");
        COMPANY_RULES.put("tvchosun", "TV조선");
        COMPANY_RULES.put("gukjenews", "국제뉴스");
        COMPANY_RULES.put("edaily", "이데일리");
        COMPANY_RULES.put("news.tf", "더팩트");
        COMPANY_RULES.put("ohmynews", "오마이뉴스");
        COMPANY_RULES.put("dailian", "데일리안");
        COMPANY_RULES.put("asiae", "아시아경제");
        COMPANY_RULES.put("inews24", "아이뉴스24");
        COMPANY_RULES.put("pressian", "프레시안");
        COMPANY_RULES.put("www.mt", "머니투데이");
        COMPANY_RULES.put("breaknews", "브레이크뉴스");
        COMPANY_RULES.put("imbc", "MBC");
        COMPANY_RULES.put("kyeonggi", "경기일보");
        COMPANY_RULES.put("radio.ytn.co.kr", "YTN 라디오");
        COMPANY_RULES.put("www.ytn.co.kr", "YTN");
        COMPANY_RULES.put("www.fnnews.com", "파이낸셜뉴스");
        COMPANY_RULES.put("mbn.mk.co.kr", "MBN");
        COMPANY_RULES.put("www.mk.co.kr", "매일경제");
        COMPANY_RULES.put("www.lawissue.co.kr", "로이슈");
        COMPANY_RULES.put("biz.sbs.co.kr", "SBS Biz");
        COMPANY_RULES.put("news.sbs.co.kr", "SBS 뉴스");
        COMPANY_RULES.put("www.newscj.com", "천지일보");
        COMPANY_RULES.put("news.jtbc.co.kr", "JTBC");
        COMPANY_RULES.put("www.joongang.co.kr", "중앙일보");
        COMPANY_RULES.put("www.segye.com", "세계일보");
        COMPANY_RULES.put("www.kado.net", "강원도민일보");
        COMPANY_RULES.put("www.munhwa.com", "문화일보");
        COMPANY_RULES.put("www.hani.co.kr", "한겨레");
        COMPANY_RULES.put("vop.co.kr", "민중의소리");
        COMPANY_RULES.put("www.seoul.co.kr", "서울신문");
        COMPANY_RULES.put("www.sedaily.com", "서울경제");
        COMPANY_RULES.put("news.bbsi.co.kr", "BBS NEWS");
        COMPANY_RULES.put("www.imaeil.com", "매일신문");
        COMPANY_RULES.put("www.sisajournal.com", "시사저널");
        COMPANY_RULES.put("www.jeonmae.co.kr", "전국매일신문");
        COMPANY_RULES.put("www.newstnt.com", "뉴스티앤티");
        COMPANY_RULES.put("biz.chosun.com", "조선비즈");
        COMPANY_RULES.put("weekly.chosun.com", "주간조선");
        COMPANY_RULES.put("monthly.chosun.com", "월간조선");
        COMPANY_RULES.put("www.chosun.com", "조선일보");
        COMPANY_RULES.put("www.ikbc.co.kr", "KBC광주방송");
        COMPANY_RULES.put("www.joongdo.co.kr", "중도일보");
        COMPANY_RULES.put("www.hankyung.com", "한국경제");
        COMPANY_RULES.put("www.hankookilbo.com", "한국일보");
        COMPANY_RULES.put("cc.newdaily.co.kr", "뉴데일리 충청세종");
        COMPANY_RULES.put("tk.newdaily.co.kr", "뉴데일리 대구경북");
        COMPANY_RULES.put("gg.newdaily.co.kr", "뉴데일리 경기인천");
        COMPANY_RULES.put("gj.newdaily.co.kr", "뉴데일리 광주전남");
        COMPANY_RULES.put("www.newdaily.co.kr", "뉴데일리");
        COMPANY_RULES.put("sports.donga.com", "스포츠동아");
        COMPANY_RULES.put("www.donga.com", "동아일보");
        COMPANY_RULES.put("www.kwnews.co.kr", "강원일보");
        COMPANY_RULES.put("www.ichannela.com", "채널A");
        COMPANY_RULES.put("www.ajunews.com", "아주경제");
        COMPANY_RULES.put("sports.khan.co.kr", "스포츠경향");
        COMPANY_RULES.put("www.khan.co.kr", "경향신문");
        COMPANY_RULES.put("www.polinews.co.kr", "폴리뉴스");
        COMPANY_RULES.put("www.wikitree.co.kr", "위키트리");
        COMPANY_RULES.put("www.busan.com", "부산일보");
        COMPANY_RULES.put("www.daejonilbo.com", "대전일보");
        COMPANY_RULES.put("www.goodmorningcc.com", "굿모닝충청");
        COMPANY_RULES.put("www.hansbiz.co.kr", "한스경제");
        COMPANY_RULES.put("www.shinailbo.co.kr", "신아일보");
        COMPANY_RULES.put("www.kihoilbo.co.kr", "기호일보");
        COMPANY_RULES.put("www.sejungilbo.com", "세종일보");
        COMPANY_RULES.put("www.dt.co.kr", "디지털타임스");
        COMPANY_RULES.put("www.chungnamilbo.co.kr", "충남일보");
        COMPANY_RULES.put("www.ccnnews.co.kr", "충청뉴스");
        COMPANY_RULES.put("www.kukinews.com", "쿠키뉴스");
        COMPANY_RULES.put("www.sidae.com", "시대일보");
        COMPANY_RULES.put("daily.hankooki.com", "데일리한국");
        COMPANY_RULES.put("weekly.hankooki.com", "주간한국");
        COMPANY_RULES.put("www.kgnews.co.kr", "경기신문");
        COMPANY_RULES.put("www.jibs.co.kr", "JIBS");
        COMPANY_RULES.put("www.m-economynews.com", "M이코노미뉴스");
        COMPANY_RULES.put("www.meconomynews.com", "M이코노미뉴스");
        COMPANY_RULES.put("www.yonhapnewstv.co.kr", "연합뉴스TV");
        COMPANY_RULES.put("www.segyebiz.com", "세계비즈");
        COMPANY_RULES.put("www.ccdailynews.com", "충청일보");
        COMPANY_RULES.put("www.sisafocus.co.kr", "시사포커스");
        COMPANY_RULES.put("www.mediatoday.co.kr", "미디어오늘");
        COMPANY_RULES.put("www.newstomato.com", "뉴스토마토");
        COMPANY_RULES.put("www.m-i.kr", "매일일보");
        COMPANY_RULES.put("www.joongboo.com", "중부일보");
        COMPANY_RULES.put("www.ggilbo.com", "금강일보");
        COMPANY_RULES.put("www.etnews.com", "전자신문");
        COMPANY_RULES.put("www.dtnews24.com", "디트뉴스24");
        COMPANY_RULES.put("www.namdonews.com", "남도일보");
        COMPANY_RULES.put("www.hidomin.com", "경북도민일보");
        COMPANY_RULES.put("www.kbmaeil.com", "경북매일");
        COMPANY_RULES.put("www.ibabynews.com", "베이비뉴스");
        COMPANY_RULES.put("www.newsworker.co.kr", "뉴스워커");
        COMPANY_RULES.put("www.ccdn.co.kr", "충청매일");
        COMPANY_RULES.put("www.kdpress.co.kr", "데일리경제");
        COMPANY_RULES.put("www.kmib.co.kr", "국민일보");
        COMPANY_RULES.put("www.thepublic.kr", "더퍼블릭");
        COMPANY_RULES.put("www.ksmnews.co.kr", "경상매일신문");
        COMPANY_RULES.put("www.enewstoday.co.kr", "이뉴스투데이");
        COMPANY_RULES.put("www.kookje.co.kr", "국제신문");
        COMPANY_RULES.put("www.etoday.co.kr", "이투데이");
        COMPANY_RULES.put("www.headlinejeju.co.kr", "헤드라인제주");
        COMPANY_RULES.put("www.dnews.co.kr", "대한경제");
        COMPANY_RULES.put("www.newsfreezone.co.kr", "뉴스프리존");
        COMPANY_RULES.put("www.kyongbuk.co.kr", "경북일보");
        COMPANY_RULES.put("www.viva100.com", "브릿지경제");
        COMPANY_RULES.put("www.pennmike.com", "펜앤드마이크");
        COMPANY_RULES.put("www.gndomin.com", "경남도민신문");
        COMPANY_RULES.put("www.pinpointnews.co.kr", "핀포인트뉴스");
        COMPANY_RULES.put("www.eroun.net", "이로운넷");
        COMPANY_RULES.put("www.cctimes.kr", "충청타임즈");
        COMPANY_RULES.put("news.mtn.co.kr", "머니투데이방송");
        COMPANY_RULES.put("news.lghellovision.net", "LG헬로비전");
        COMPANY_RULES.put("www.joseilbo.com", "조세일보");
        COMPANY_RULES.put("www.lawleader.co.kr", "로리더");
        COMPANY_RULES.put("www.incheonilbo.com", "인천일보");
        COMPANY_RULES.put("www.jemin.com", "제민일보");
        COMPANY_RULES.put("www.gnnews.co.kr", "경남신문");
        COMPANY_RULES.put("zdnet.co.kr", "ZDNet Korea");
        COMPANY_RULES.put("www.jnilbo.com", "전남일보");
        COMPANY_RULES.put("www.newsjeju.net", "뉴스제주");
        COMPANY_RULES.put("www.newsworks.co.kr", "뉴스웍스");
        COMPANY_RULES.put("www.kjdaily.com", "광주매일신문");
        COMPANY_RULES.put("www.fntoday.co.kr", "파이낸스투데이");
        COMPANY_RULES.put("www.jbnews.com", "중부매일");
        COMPANY_RULES.put("www.sentv.co.kr", "서울경제TV");
        COMPANY_RULES.put("news.skbroadband.com", "B tv news");
        COMPANY_RULES.put("www.metroseoul.co.kr", "메트로신문");
        COMPANY_RULES.put("www.inews365.com", "충북일보");
        COMPANY_RULES.put("www.cnbnews.com", "CNB뉴스");
        COMPANY_RULES.put("weekly.cnbnews.com", "CNB뉴스");
        COMPANY_RULES.put("www.kyeongin.com", "경인일보");
        COMPANY_RULES.put("www.incheontoday.com", "인천투데이");
        COMPANY_RULES.put("www.dynews.co.kr", "동양일보");
        COMPANY_RULES.put("www.jeonmin.co.kr", "전민일보");
        COMPANY_RULES.put("www.newsgn.com", "뉴스경남");
        COMPANY_RULES.put("www.viewsnnews.com", "뷰스앤뉴스");
        COMPANY_RULES.put("www.domin.co.kr", "전북도민일보");
        COMPANY_RULES.put("www.siminilbo.co.kr", "시민일보");
        COMPANY_RULES.put("www.jejusori.net", "제주의소리");
        COMPANY_RULES.put("www.natv.go.kr", "국회방송");
        COMPANY_RULES.put("www.pointdaily.co.kr", "포인트데일리");
        COMPANY_RULES.put("www.jndn.com", "전남매일");
        COMPANY_RULES.put("facttv.kr", "팩트TV");
        COMPANY_RULES.put("www.businesspost.co.kr", "비즈니스포스트");
        COMPANY_RULES.put("www.news2day.co.kr", "뉴스투데이");
        COMPANY_RULES.put("www.gnmaeil.com", "경남매일");
        COMPANY_RULES.put("www.womennews.co.kr", "여성신문");
        COMPANY_RULES.put("www.kpinews.kr", "KPI뉴스");
        COMPANY_RULES.put("www.mbn.co.kr", "MBN");
        COMPANY_RULES.put("www.obsnews.co.kr", "OBS경인TV");
        COMPANY_RULES.put("www.bzeronews.com", "비제로뉴스");
        COMPANY_RULES.put("www.weeklytoday.com", "위클리오늘");
        COMPANY_RULES.put("www.energydaily.co.kr", "에너지데일리");
        COMPANY_RULES.put("www.safetimes.co.kr", "세이프타임즈");
        COMPANY_RULES.put("www.jeollailbo.com", "전라일보");
        COMPANY_RULES.put("www.asiatoday.co.kr", "아시아투데이");
        COMPANY_RULES.put("www.kmaeil.com", "경인매일");
        COMPANY_RULES.put("www.ppss.kr", "ㅍㅍㅅㅅ");
        COMPANY_RULES.put("www.dkilbo.com", "대경일보");
        COMPANY_RULES.put("www.kbsm.net", "경북신문");
        COMPANY_RULES.put("www.g1tv.co.kr", "G1방송");
        COMPANY_RULES.put("dgmbc.com", "대구MBC");
        COMPANY_RULES.put("www.onews.tv", "원뉴스");
        COMPANY_RULES.put("www.youthdaily.co.kr", "청년일보");
        COMPANY_RULES.put("www.ujeil.com", "울산제일일보");
        COMPANY_RULES.put("www.idomin.com", "경남도민일보");
        COMPANY_RULES.put("www.ddaily.co.kr", "디지털데일리");
        COMPANY_RULES.put("www.cjb.co.kr", "CJB청주방송");
        COMPANY_RULES.put("www.paxetv.com", "팍스경제TV");
        COMPANY_RULES.put("www.straightnews.co.kr", "스트레이트뉴스");
        COMPANY_RULES.put("www.kfenews.co.kr", "금융경제신문");
        COMPANY_RULES.put("www.financialreview.co.kr", "파이낸셜리뷰");
        COMPANY_RULES.put("www.sportsseoul.com", "스포츠서울");
        COMPANY_RULES.put("www.ekn.kr", "에너지경제");
        COMPANY_RULES.put("kjmbc.co.kr", "광주MBC");
        COMPANY_RULES.put("www.ilyoseoul.co.kr", "일요서울");
        COMPANY_RULES.put("www.nbntv.kr", "NBN뉴스");
        COMPANY_RULES.put("www.samdailbo.com", "삼다일보");
        COMPANY_RULES.put("www.medigatenews.com", "메디게이트뉴스");
        COMPANY_RULES.put("www.thepowernews.co.kr", "더파워");
        COMPANY_RULES.put("www.ulsanpress.net", "울산신문");
        COMPANY_RULES.put("www.jjan.kr", "전북일보");
        COMPANY_RULES.put("www.taxtimes.co.kr", "한국세정신문");
        COMPANY_RULES.put("www.mediapen.com", "미디어펜");
        COMPANY_RULES.put("www.ddanzi.com", "딴지일보");
        COMPANY_RULES.put("news.knn.co.kr", "KNN");
        COMPANY_RULES.put("www.ablenews.co.kr", "에이블뉴스");
        COMPANY_RULES.put("www.whosaeng.com", "후생신보");
        COMPANY_RULES.put("www.getnews.co.kr", "글로벌경제신문");
        COMPANY_RULES.put("www.mediaus.co.kr", "미디어스");
        COMPANY_RULES.put("www.ksilbo.co.kr", "경상일보");
        COMPANY_RULES.put("tjmbc.co.kr", "대전MBC");
        COMPANY_RULES.put("www.jmbc.co.kr", "전주MBC");
        COMPANY_RULES.put("www.doctorsnews.co.kr", "의협신문");
        COMPANY_RULES.put("www.idaegu.co.kr", "대구신문");
        COMPANY_RULES.put("www.seoulwire.com", "서울와이어");
        COMPANY_RULES.put("www.insight.co.kr", "인사이트");
        COMPANY_RULES.put("www.slist.kr", "싱글리스트");
        COMPANY_RULES.put("www.newstown.co.kr", "뉴스타운");
        COMPANY_RULES.put("www.newsprime.co.kr", "프라임경제");
        COMPANY_RULES.put("www.cctoday.co.kr", "충청투데이");
        COMPANY_RULES.put("news.einfomax.co.kr", "연합인포맥스");
        COMPANY_RULES.put("www.job-post.co.kr", "잡포스트");
        COMPANY_RULES.put("www.goodkyung.com", "굿경제");
        COMPANY_RULES.put("www.safetynews.co.kr", "안전신문");
        COMPANY_RULES.put("www.mhns.co.kr", "문화뉴스");
        COMPANY_RULES.put("www.mdilbo.com", "무등일보");
        COMPANY_RULES.put("www.ttlnews.com", "TTL뉴스");
        COMPANY_RULES.put("www.nspna.com", "NSP통신");
        COMPANY_RULES.put("www.g-enews.com", "글로벌이코노믹");
        COMPANY_RULES.put("sjbnews.com", "새전북신문");
        COMPANY_RULES.put("news.mbccb.co.kr", "MBC충북");
        COMPANY_RULES.put("www.medipana.com", "메디파나뉴스");
        COMPANY_RULES.put("www.aflnews.co.kr", "아시아타임즈");
        COMPANY_RULES.put("www.econonews.co.kr", "이코노뉴스");
        COMPANY_RULES.put("www.labortoday.co.kr", "매일노동뉴스");
        COMPANY_RULES.put("www.cbci.co.kr", "CBC뉴스");
        COMPANY_RULES.put("www.energy-news.co.kr", "에너지신문");
        COMPANY_RULES.put("www.bosa.co.kr", "의학신문");
        COMPANY_RULES.put("www.geconomy.co.kr", "지이코노미");
        COMPANY_RULES.put("new.dailypharm.com", "데일리팜");
        COMPANY_RULES.put("www.dailypharm.com", "데일리팜");
        COMPANY_RULES.put("wemakenews.co.kr", "위메이크뉴스");
        COMPANY_RULES.put("www.aptn.co.kr", "아파트뉴스");
        COMPANY_RULES.put("news.dealsitetv.com", "딜사이트TV");
        COMPANY_RULES.put("www.suwonilbo.kr", "수원일보");
        COMPANY_RULES.put("www.sisaweek.com", "시사위크");
        COMPANY_RULES.put("www.bizwnews.com", "비즈월드");
        COMPANY_RULES.put("www.nongmin.com", "농민신문");
        COMPANY_RULES.put("www.dailymedi.com", "데일리메디");
        COMPANY_RULES.put("news.ifm.kr", "경인방송");
        COMPANY_RULES.put("www.sportschosun.com", "스포츠조선");
        COMPANY_RULES.put("www.tfmedia.co.kr", "조세금융신문");
        COMPANY_RULES.put("fpn119.co.kr", "소방방재신문");
        COMPANY_RULES.put("www.doctorstimes.com", "닥터스타임즈");
        COMPANY_RULES.put("www.kwangju.co.kr", "광주일보");
        COMPANY_RULES.put("www.electimes.com", "전기신문");
        COMPANY_RULES.put("www.newsway.co.kr", "뉴스웨이");
        COMPANY_RULES.put("www.incheonin.com", "인천in");
        COMPANY_RULES.put("www.ccreview.co.kr", "충청리뷰");
        COMPANY_RULES.put("www.newsroad.co.kr", "뉴스로드");
        COMPANY_RULES.put("www.dailybrief.co.kr", "데일리브리프");
        COMPANY_RULES.put("andongmbc.co.kr", "안동MBC");
        COMPANY_RULES.put("www.tbc.co.kr", "TBC대구방송");
        COMPANY_RULES.put("www.sportsworldi.com", "스포츠월드");
        COMPANY_RULES.put("www.lawtimes.co.kr", "법률신문");
        COMPANY_RULES.put("economist.co.kr", "이코노미스트");
        COMPANY_RULES.put("www.agrinet.co.kr", "한국농어민신문");
        COMPANY_RULES.put("www.yeongnam.com", "영남일보");
        COMPANY_RULES.put("www.womaneconomy.co.kr", "여성경제신문");
        COMPANY_RULES.put("www.tjb.co.kr", "TJB대전방송");
        COMPANY_RULES.put("www.kpanews.co.kr", "약사공론");
        COMPANY_RULES.put("www.k-health.com", "헬스경향");
        COMPANY_RULES.put("www.jejumaeil.net", "제주매일");
        COMPANY_RULES.put("www.gasnews.com", "가스신문");
        COMPANY_RULES.put("www.huffingtonpost.kr", "허프포스트코리아");
        COMPANY_RULES.put("www.ilyosisa.co.kr", "일요시사");
        COMPANY_RULES.put("news.cpbc.co.kr", "가톨릭평화신문");
        COMPANY_RULES.put("www.fntimes.com", "한국금융신문");
        COMPANY_RULES.put("www.knnews.co.kr", "경남신문");
        COMPANY_RULES.put("www.sisain.co.kr", "시사IN");
        COMPANY_RULES.put("www.mediajeju.com", "미디어제주");
        COMPANY_RULES.put("www.newscape.co.kr", "뉴스케이프");
        COMPANY_RULES.put("www.asiatime.co.kr", "아시아타임즈");
        COMPANY_RULES.put("www.sisaon.co.kr", "시사오늘");
        COMPANY_RULES.put("www.digitaltoday.co.kr", "디지털투데이");
        COMPANY_RULES.put("mdtoday.co.kr", "메디컬투데이");
        // TODO: 필요한 언론사 매핑을 여기에 계속 추가

    }

    private NewsCompanyMapper() {
    }

    public static String resolve(String url) {
        if (url == null || url.isBlank()) {
            return "언론사 미상";
        }

        for (Map.Entry<String, String> entry : COMPANY_RULES.entrySet()) {
            if (url.contains(entry.getKey())) {
                return entry.getValue();
            }
        }

        return "언론사 미상";
    }
}
